behaviors:
  Ball:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 8196
      learning_rate: 0.003
      beta: 0.003
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 32
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 1000
    max_steps: 70000000
    time_horizon: 200
    summary_freq: 10000