behaviors:
  ArcadeDriver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 2.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory_size: 256
      sequence_length: 64
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    keep_checkpoints: 1000
    max_steps: 70000000
    time_horizon: 64
    summary_freq: 25000